//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "AmapCoreFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface AmapCoreFluttifyPlugin (SubHandlerCustom)
- (NSDictionary<NSString*, Handler>*) getSubHandlerCustom;
@end

NS_ASSUME_NONNULL_END
