//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "AmapCoreFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface AmapCoreFluttifyPlugin (SubHandler0)
- (NSDictionary<NSString*, Handler>*) getSubHandler0;
@end

NS_ASSUME_NONNULL_END
