// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum AMapRouteSearchType {
  AMapRouteSearchTypeDriving /* 0 */,
  AMapRouteSearchTypeTransit /* 1 */,
  AMapRouteSearchTypeWalking /* 2 */
}