// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum AMapCoordinateType {
  AMapCoordinateTypeAMap /* -1 */,
  AMapCoordinateTypeBaidu /* 0 */,
  AMapCoordinateTypeMapBar /* 0 */,
  AMapCoordinateTypeMapABC /* 0 */,
  AMapCoordinateTypeSoSoMap /* 0 */,
  AMapCoordinateTypeAliYun /* 0 */,
  AMapCoordinateTypeGoogle /* 0 */,
  AMapCoordinateTypeGPS /* 0 */
}