// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum AMapTransitStrategy {
  AMapTransitStrategyFastest /* 0 */,
  AMapTransitStrategyMinFare /* 1 */,
  AMapTransitStrategyMinTransfer /* 2 */,
  AMapTransitStrategyMinWalk /* 3 */,
  AMapTransitStrategyMostComfortable /* 4 */,
  AMapTransitStrategyAvoidSubway /* 5 */
}