// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum AMapDrivingStrategy {
  AMapDrivingStrategyFastest /* 0 */,
  AMapDrivingStrategyMinFare /* 1 */,
  AMapDrivingStrategyShortest /* 2 */,
  AMapDrivingStrategyNoHighways /* 3 */,
  AMapDrivingStrategyAvoidCongestion /* 4 */,
  AMapDrivingStrategyAvoidHighwaysAndFare /* 5 */,
  AMapDrivingStrategyAvoidHighwaysAndCongestion /* 6 */,
  AMapDrivingStrategyAvoidFareAndCongestion /* 7 */,
  AMapDrivingStrategyAvoidHighwaysAndFareAndCongestion /* 8 */
}